%% =================================NOTE 1==================================
%% 								Need more tests
%% =================================NOTE 2==================================
%% Most of the reference values were generated by the DeepSeek AI
%% in the step-by-step reasoning mode. The AI was fed matrices and
%% white points, but not actual algorithms used in this app, so they were
%% calculated by the AI's own algoritms, to avoid using the results of
%% potentially incorrect algorithms as the reference values for testing the
%% same algorithms.
%% Some tests have permssible margins of error somewhat greater than
%% they supposed to be for the 100% ideal reference data, but unfortunatelly
%% AI rounds off intermediate values too often and too early (checked by
%% looking at the AI reasoning and manually recalculating the displayed
%% formulas step by step), so the error in the reference values can be
%% greater than it should be for the "true" reference values, and the
%% calculated values almost always seem more correct.
%% =================================NOTE /==================================

-module(cbet_test).
-include_lib("eunit/include/eunit.hrl").
-include("cbet.hrl").


-record(color_etalon, {
	name :: string(),
	srgb :: #srgb{},
	hsv :: #hsv{},
	hsl :: #hsl{},
	hsi :: #hsi{},
	xyzd65 :: #xyz{},
	xyzd50 :: #xyz{},
	lab_d65 :: #lab{},
	luv_d65 :: #luv{},
	lab_d50 :: #lab{},
	luv_d50 :: #luv{},
	cmy :: #cmy{},
	adobe_rgb :: #adobe_rgb{},
	display_p3 :: #display_p3{},
	adobe_rgb_out_of_gamut :: #adobe_rgb{},
	rec2020 :: #rec2020{},
	rec709 :: #rec2020{},
	prophoto_rgb :: #prophoto_rgb{},
	wide_gamut_rgb :: #wide_gamut_rgb{},
	hwb :: #hwb{},
	ipt :: #ipt{},
	xyy :: #xyy{},
	lchuv :: #lchuv{},
	logluv :: #logluv{},
	din99d_lab :: #din99_lab{},
	lch :: #lch{},
	oklab :: #oklab{},
	oklch :: #oklch{},
	ictcp_pq :: #ictcp{}
}).

etalon_colors() ->
	[
		#color_etalon{
			name = "white",
			srgb = #srgb{r = 1.0, g = 1.0, b = 1.0},
			hsv = #hsv{h = 0.0, s = 0.0, v = 1.0},
			hsl = #hsl{h = 0.0, s = 0.0, l = 1.0},
			hsi = #hsi{h = 0.0, s = 0.0, i = 1.0},
			hwb = #hwb{h = 0.0, w = 1.0, b = 0.0},
			ipt = #ipt{i = 1.0, p = 0.0, t = 0.0},
			xyzd65 = #xyz{x = 95.047, y = 100.000, z = 108.883, illum = ?ILLUM_D65},
			xyzd50 = #xyz{x = 96.422, y = 100.000, z = 82.521, illum = ?ILLUM_D50},
			lab_d65 = #lab{l = 100.0, a = 0.0, b = 0.0, illum = ?ILLUM_D65},
			luv_d65 = #luv{l = 100.0, u = 0.0, v = 0.0, illum = ?ILLUM_D65},
			lab_d50 = #lab{l = 100.0, a = 0.005, b = -0.010, illum = ?ILLUM_D50},  %% адаптация Bradford
			luv_d50 = #luv{l = 100.0, u = 0.0, v = 0.0, illum = ?ILLUM_D50},
			cmy = #cmy{illum = ?ILLUM_D65, c = 0.0, m = 0.0, y = 0.0},
			adobe_rgb = #adobe_rgb{illum = ?ILLUM_D65, r = 1.0, g = 1.0, b = 1.0},
			display_p3 = #display_p3{illum = ?ILLUM_D65, r = 1.0, g = 1.0, b = 1.0},
			rec2020 = #rec2020{r = 1.0, g = 1.0, b = 1.0},
			rec709 = #rec709{r = 1.0, g = 1.0, b = 1.0},
			prophoto_rgb = #prophoto_rgb{r = 1.0, g = 1.0, b = 1.0},
			wide_gamut_rgb = #wide_gamut_rgb{r = 1.0, g = 1.0, b = 1.0},
			xyy = #xyy{x = 0.3127, y = 0.3290,  luminance = 100.0},
			lchuv = #lchuv{l = 100.0, c = 0.0, h = 0.0},
			logluv = #logluv{l = 70.644, u = 81, v = 192},
			din99d_lab = #din99_lab{l = 100.0, a = 0.0, b = 0.0},
			lch = #lch{l = 100.0, c = 0.0, h = 0.0},
			oklab = #oklab{l = 1.0, a = 0.0, b = 0.0},
			oklch = #oklch{l = 1.0, c = 0.0, h = 0.0},
			ictcp_pq = #ictcp{i = 0.15, ct = 0.0, cp = 0.0}
		},
		#color_etalon{
			name = "black",
			srgb = #srgb{r = 0.0, g = 0.0, b = 0.0},
			hsv = #hsv{h = 0.0, s = 0.0, v = 0.0},
			hsl = #hsl{h = 0.0, s = 0.0, l = 0.0},
			hsi = #hsi{h = 0.0, s = 0.0, i = 0.0},
			hwb = #hwb{h = 0.0, w = 0.0, b = 1.0},
			ipt = #ipt{i = 0.0, p = 0.0, t = 0.0},
			xyzd65 = #xyz{x = 0.0, y = 0.0, z = 0.0, illum = ?ILLUM_D65},
			xyzd50 = #xyz{x = 0.0, y = 0.0, z = 0.0, illum = ?ILLUM_D50},
			lab_d65 = #lab{l = 0.0, a = 0.0, b = 0.0, illum = ?ILLUM_D65},
			luv_d65 = #luv{l = 0.0, u = 0.0, v = 0.0, illum = ?ILLUM_D65},
			lab_d50 = #lab{l = 0.0, a = 0.0, b = 0.0, illum = ?ILLUM_D50},
			luv_d50 = #luv{l = 0.0, u = 0.0, v = 0.0, illum = ?ILLUM_D50},
			cmy = #cmy{illum = ?ILLUM_D65, c = 1.0, m = 1.0, y = 1.0},
			adobe_rgb = #adobe_rgb{illum = ?ILLUM_D65, r = 0.0, g = 0.0, b = 0.0},
			display_p3 = #display_p3{illum = ?ILLUM_D65, r = 0.0, g = 0.0, b = 0.0},
			rec2020 = #rec2020{r = 0.0, g = 0.0, b = 0.0},
			rec709 = #rec709{r = 0.0, g = 0.0, b = 0.0},
			prophoto_rgb = #prophoto_rgb{r = 0.0, g = 0.0, b = 0.0},
			wide_gamut_rgb = #wide_gamut_rgb{r = 0.0, g = 0.0, b = 0.0},
			xyy = #xyy{x = 0.0, y = 0.0,  luminance = 0.0},
			lchuv = #lchuv{l = 0.0, c = 0.0, h = 0.0},
			logluv = #logluv{l = 44.07, u = 0.0, v = 0.0},
			din99d_lab = #din99_lab{l = 0.0, a = 0.0, b = 0.0},
			lch = #lch{l = 0.0, c = 0.0, h = 0.0},
			oklab = #oklab{l = 0.0, a = 0.0, b = 0.0},
			oklch = #oklch{l = 0.0, c = 0.0, h = 0.0},
			ictcp_pq = #ictcp{i = 0.0, ct = 0.0, cp = 0.0}
		},
		#color_etalon{
			name = "gray",
			srgb = #srgb{r = 0.5, g = 0.5, b = 0.5},
			hsv = #hsv{h = 0.0, s = 0.0, v = 0.5},
			hsl = #hsl{h = 0.0, s = 0.0, l = 0.5},
			hsi = #hsi{h = 0.0, s = 0.0, i = 0.5},
			hwb = #hwb{h = 0.0, w = 0.5, b = 0.5},
			ipt = #ipt{i = 0.5148, p = 0.0, t = 0.0},
			cmy = #cmy{illum = ?ILLUM_D65, c = 0.786, m = 0.786, y = 0.786},
			lab_d50 = #lab{l = 53.39, a = 0.0, b = 0.0, illum = ?ILLUM_D50},
			adobe_rgb = #adobe_rgb{illum = ?ILLUM_D65, r = 0.498094, g = 0.498094, b = 0.498094},
			display_p3 = #display_p3{illum = ?ILLUM_D65, r = 0.502, g = 0.502, b = 0.502},
			rec2020 = #rec2020{r = 0.45, g = 0.45, b = 0.45},
			rec709 = #rec709{r = 0.4501, g = 0.4501, b = 0.4501},
			prophoto_rgb = #prophoto_rgb{r = 0.4245, g = 0.4245, b = 0.4245},
			wide_gamut_rgb = #wide_gamut_rgb{r = 0.4959, g = 0.4959, b = 0.4959},
			logluv = #logluv{l = 68.42, u = 81.1, v = 192.0},
			din99d_lab = #din99_lab{l = 57.17, a = 0.0, b = 0.0},
			lch = #lch{l = 53.4, c = 0.0, h = 0.0},
			oklab = #oklab{l = 0.598, a = 0.0, b = 0.0},
			oklch = #oklch{l = 0.598, c = 0.0, h = 0.0},
			ictcp_pq = #ictcp{i = 0.0851, ct = 0.0, cp = 0.0}

		},
		#color_etalon{
			name = "red",
			srgb = #srgb{r = 1.0, g = 0.0, b = 0.0},
			hsv = #hsv{h = 0.0, s = 1.0, v = 1.0},
			hsl = #hsl{h = 0.0, s = 1.0, l = 0.5},
			hsi = #hsi{h = 0.0, s = 1.0, i = 0.333333333333},
			hwb = #hwb{h = 0.0, w = 0.0, b = 0.0},
			ipt = #ipt{i = 0.46, p = 0.62, t = 0.44},
			xyzd65 = #xyz{x = 41.240, y = 21.260, z = 1.930, illum = ?ILLUM_D65},
			xyzd50 = #xyz{x = 43.6046, y = 22.2480, z = 1.3933, illum = ?ILLUM_D50},
			lab_d65 = #lab{l = 53.232, a = 80.109, b = 67.220, illum = ?ILLUM_D65},
			luv_d65 = #luv{l = 53.232, u = 175.015, v = 37.753, illum = ?ILLUM_D65},
			lab_d50 = #lab{l = 54.29, a = 80.87, b = 69.89, illum = ?ILLUM_D50},
			luv_d50 = #luv{l = 54.29, u = 175.03, v = 25.96, illum = ?ILLUM_D50},
			cmy = #cmy{illum = ?ILLUM_D65, c = 0.0, m = 1.0, y = 1.0},
			adobe_rgb = #adobe_rgb{illum = ?ILLUM_D65, r = 0.8586, g = 0.0, b = 0.0},
			lchuv = #lchuv{l = 54.3, c = 177.1, h = 8.5},
			din99d_lab = #din99_lab{l = 58.059, a = 34.78, b = 28.771134},
			ictcp_pq = #ictcp{i = 0.0858, ct = -0.0263, cp = 0.0989}

		},
		#color_etalon{
			name = "green",
			srgb = #srgb{r = 0.0, g = 1.0, b = 0.0},
			hsv = #hsv{h = 120.0, s = 1.0, v = 1.0},
			hsl = #hsl{h = 120.0, s = 1.0, l = 0.5},
			hsi = #hsi{h = 120.0, s = 1.0, i = 0.333333333333},
			hwb = #hwb{h = 120.0, w = 0.0, b = 0.0},
			ipt = #ipt{i = 0.76, p = -0.45, t = 0.53},
			xyzd65 = #xyz{x = 35.760, y = 71.520, z = 11.920, illum = ?ILLUM_D65},
			xyzd50 = #xyz{x = 38.512, y = 71.695, z = 9.712, illum = ?ILLUM_D50},
			lab_d65 = #lab{l = 87.737, a = -86.185, b = 83.181, illum = ?ILLUM_D65},
			luv_d65 = #luv{l = 87.737, u = -83.077, v = 107.398, illum = ?ILLUM_D65},
			lab_d50 = #lab{l = 87.82, a = -79.45, b = 80.99, illum = ?ILLUM_D50},
			luv_d50 = #luv{l = 87.82, u = -84.96, v = 87.26, illum = ?ILLUM_D50},
			cmy = #cmy{illum = ?ILLUM_D65, c = 1.0, m = 0.0, y = 1.0},
			adobe_rgb = undefined,
			display_p3 = undefined,
			rec2020 = #rec2020{r = 0.568, g = 0.959, b = 0.269},
			rec709 = #rec709{r = 0.0, g = 1.0, b = 0.0},
			prophoto_rgb = #prophoto_rgb{r = 0.5400, g = 0.9275, b = 0.3047},
			wide_gamut_rgb = #wide_gamut_rgb{r = 0.6630, g = 0.9254, b = 0.2965},
			lch = #lch{l = 87.74, c = 119.74, h = 136.0}

		},
		#color_etalon{
			name = "blue",
			srgb = #srgb{r = 0.0, g = 0.0, b = 1.0},
			hsv = #hsv{h = 240.0, s = 1.0, v = 1.0},
			hsl = #hsl{h = 240.0, s = 1.0, l = 0.5},
			hsi = #hsi{h = 240.0, s = 1.0, i = 0.333333333333},
			hwb = #hwb{h = 240.0, w = 0.0, b = 0.0},
			ipt = #ipt{i = 0.44, p = -0.24, t = -0.75},
			xyzd65 = #xyz{x = 18.044, y = 7.218, z = 95.030, illum = ?ILLUM_D65},
			xyzd50 = #xyz{x = 14.300, y = 6.061, z = 71.420, illum = ?ILLUM_D50},
			lab_d65 = #lab{l = 32.30, a = 79.20, b = -107.87, illum = ?ILLUM_D65},
			luv_d65 = #luv{l = 32.30, u = -9.41, v = -130.36, illum = ?ILLUM_D65},
			lab_d50 = #lab{l = 29.57, a = 68.24, b = -112.0, illum = ?ILLUM_D50},
			luv_d50 = #luv{l = 29.57, u = -11.56, v = -121.98, illum = ?ILLUM_D50},
			cmy = #cmy{illum = ?ILLUM_D65, c = 1.0, m = 1.0, y = 0.0},
			adobe_rgb = #adobe_rgb{illum = ?ILLUM_D65, r = 0.0, g = 0.0, b = 0.98107},
			xyy = #xyy{x = 0.1500, y = 0.0600,  luminance = 7.22},
			logluv = #logluv{l = 66.85, u = 71.95, v = 64.74},
			oklab = #oklab{l = 0.452, a = -0.032, b = -0.312},
			oklch = #oklch{l = 0.452, c = 0.314, h = 264.1}
		},
		#color_etalon{
			name = "yellow",
			srgb = #srgb{r = 1.0, g = 1.0, b = 0.0},
			hsv = #hsv{h = 60.0, s = 1.0, v = 1.0},
			hsl = #hsl{h = 60.0, s = 1.0, l = 0.5},
			hsi = #hsi{h = 60.0, s = 1.0, i = 0.666666666667},
			hwb = #hwb{h = 60.0, w = 0.0, b = 0.0},
			ipt = #ipt{i = 0.86, p = -0.11, t = 0.65},
			xyzd65 = #xyz{x = 77.000, y = 92.780, z = 13.850, illum = ?ILLUM_D65},
			xyzd50 = #xyz{x = 82.118, y = 93.94, z = 11.101, illum = ?ILLUM_D50},
			lab_d65 = #lab{l = 97.13, a = -21.54, b = 94.49, illum = ?ILLUM_D65},
			luv_d65 = #luv{l = 97.13, u = 7.70, v = 106.75, illum = ?ILLUM_D65},
			lab_d50 = #lab{l = 97.62, a = -15.76, b = 93.42, illum = ?ILLUM_D50},
			luv_d50 = #luv{l = 97.62, u = 7.93, v = 84.48, illum = ?ILLUM_D50},
			cmy = #cmy{illum = ?ILLUM_D65, c = 0.0, m = 0.0, y = 1.0},
			adobe_rgb = #adobe_rgb{illum = ?ILLUM_D65, r = 1.0, g = 1.0, b = 0.23457},
			lchuv = #lchuv{l = 97.6, c = 84.8, h = 84.6},
			logluv = #logluv{l = 70.538, u = 83.64, v = 226.7},
			din99d_lab = #din99_lab{l = 97.94, a = -10.14, b = 43.11},
			oklab = #oklab{l = 0.968, a = -0.071, b = 0.199},
			oklch = #oklch{l = 0.968, c = 0.211, h = 109.7},
			ictcp_pq = #ictcp{i = 0.1447, ct = -0.1033, cp = 0.0168}
		},
		#color_etalon{
			name = "cyan",
			srgb = #srgb{r = 0.0, g = 1.0, b = 1.0},
			hsv = #hsv{h = 180.0, s = 1.0, v = 1.0},
			hsl = #hsl{h = 180.0, s = 1.0, l = 0.5},
			hsi = #hsi{h = 180.0, s = 1.0, i = 0.666666666667},
			ipt = #ipt{i = 0.91, p = -0.34, t = -0.14},
			xyzd65 = #xyz{x = 53.801, y = 78.737, z = 106.951, illum = ?ILLUM_D65},
			xyzd50 = #xyz{x = 52.8, y = 77.753, z = 81.141, illum = ?ILLUM_D50},
			cmy = #cmy{illum = ?ILLUM_D65, c = 1.0, m = 0.0, y = 0.0},
			lch = #lch{l = 91.14, c = 50.21, h = 196.3}
		},
		#color_etalon{
			name = "magenta",
			srgb = #srgb{r = 1.0, g = 0.0, b = 1.0},
			hsv = #hsv{h = 300.0, s = 1.0, v = 1.0},
			hsl = #hsl{h = 300.0, s = 1.0, l = 0.5},
			hsi = #hsi{h = 300.0, s = 1.0, i = 0.666666666667},
			ipt = #ipt{i = 0.67, p = 0.57, t = -0.39},
			xyzd65 = #xyz{x = 59.284, y = 28.478, z = 96.960, illum = ?ILLUM_D65},
			xyzd50 = #xyz{x = 57.904, y = 28.306, z = 72.817, illum = ?ILLUM_D50},
			cmy = #cmy{illum = ?ILLUM_D65, c = 0.0, m = 1.0, y = 0.0}

		},
		#color_etalon{
			name = "custom1",
			srgb = #srgb{r = 0.75, g = 0.25, b = 0.5},
			hsv = #hsv{h = 330.0, s = 0.666666666667, v = 0.75},
			hsl = #hsl{h = 330.0, s = 0.5, l = 0.5},
			hsi = #hsi{h = 330.0, s = 0.5, i = 0.5},
			cmy = #cmy{illum = ?ILLUM_D65, c = 0.478, m = 0.949, y = 0.786},
			lab_d65 = #lab{l = 47.36, a = 56.52, b = -8.04, illum = ?ILLUM_D65},
			adobe_rgb = #adobe_rgb{illum = ?ILLUM_D65, r = 0.64979, g = 0.25804, b = 0.49084},
			display_p3 = #display_p3{illum = ?ILLUM_D65, r = 0.6929, g = 0.2858, b = 0.4945}
		},
		#color_etalon{
			name = "custom2",
			srgb = #srgb{r = 0.3, g = 0.7, b = 0.9},
			hsv = #hsv{h = 200.0, s = 0.666666666667, v = 0.9},
			hsl = #hsl{h = 200.0, s = 0.75, l = 0.6},
			hsi = #hsi{h = 200.0, s = 0.545454545455, i = 0.633333333333},
			cmy = #cmy{illum = ?ILLUM_D65, c = 0.926, m = 0.553, y = 0.213},
			adobe_rgb = #adobe_rgb{illum = ?ILLUM_D65, r = 0.45830, g = 0.69385, b = 0.88979},
			display_p3 = #display_p3{illum = ?ILLUM_D65, r = 0.4094, g = 0.6908, b = 0.8811},
			rec2020 = #rec2020{r = 0.466, g = 0.650, b = 0.864},
			rec709 = #rec709{r = 0.2400, g = 0.6662, b = 0.8879},
			prophoto_rgb = #prophoto_rgb{r = 0.5095, g = 0.6180, b = 0.8429},
			wide_gamut_rgb = #wide_gamut_rgb{r = 0.5090, g = 0.6831, b = 0.8803},
			xyy = #xyy{x = 0.2171, y = 0.2551,  luminance = 38.78},
			ictcp_pq = #ictcp{i = 0.1078, ct = 0.0273, cp = -0.0315}
		},
		#color_etalon{ %% test only adobe -> srgb for this record
			name = "green adobe rgb (out of gamut for srgb)",
			srgb = #srgb{r = -5.1458, g = 1.0, b = -0.5549},
			adobe_rgb_out_of_gamut = #adobe_rgb{illum = ?ILLUM_D65, r = 0, g = 1, b = 0}
		},
		#color_etalon{ %% test only adobe -> srgb for this record
			name = "turquoise adobe rgb (out of gamut for srgb)",
			srgb = #srgb{r = -3.15245, g = 0.80482, b = 0.80492},
			adobe_rgb_out_of_gamut = #adobe_rgb{illum = ?ILLUM_D65, r = 0, g = 0.8, b = 0.8},
			xyy = #xyy{x = 0.1748, y =  0.3286,  luminance = 43.01}
		}
	].


srgb_to_hsv_roundtrip_test_() ->
	[srgb_to_hsv_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.hsv =/= undefined].

srgb_to_hsv_roundtrip_case(#color_etalon{name = Name, srgb = Srgb, hsv = ExpectedHsv}) ->
	fun() ->
		ConvertedHsv = cbet:convert(Srgb, #hsv{illum = ?ILLUM_D65}),
		BackSrgb = cbet:convert(ConvertedHsv, #srgb{}),

		H_diff = abs(normalize_hue_diff(ConvertedHsv#hsv.h - ExpectedHsv#hsv.h)),
		S_diff = abs(ConvertedHsv#hsv.s - ExpectedHsv#hsv.s),
		V_diff = abs(ConvertedHsv#hsv.v - ExpectedHsv#hsv.v),

		R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
		G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
		B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

		Tol = 0.001,
		TolHue = 0.1,
		TolRGB = Tol,

		case {H_diff < TolHue, S_diff < Tol, V_diff < Tol, R_diff < TolRGB, G_diff < TolRGB, B_diff < TolRGB} of
			{true, true, true, true, true, true} ->
				ok;
			_ ->
				io:format("~n=== Падение теста srgb_to_hsv_roundtrip на '~s' ===~n"
				"Вход sRGB:      ~p~n"
				"Ожидаемый HSV:  ~p~n"
				"Полученный HSV: ~p~n"
				"Разница H/S/V:  ~.4f / ~.6f / ~.6f~n"
				"Back sRGB:      ~p~n"
				"ΔR/G/B:         ~.6f / ~.6f / ~.6f (должно < ~.4f)~n~n",
					[Name, Srgb, ExpectedHsv, ConvertedHsv, H_diff, S_diff, V_diff, BackSrgb, R_diff, G_diff, B_diff, TolRGB]),
				?assert(false)
		end
	end.


srgb_to_hsl_roundtrip_test_() ->
	[srgb_to_hsl_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.hsl =/= undefined].

srgb_to_hsl_roundtrip_case(#color_etalon{name = Name, srgb = Srgb, hsl = ExpectedHsl}) ->
	fun() ->
		ConvertedHsl = cbet:convert(Srgb, #hsl{illum = ?ILLUM_D65}),
		BackSrgb = cbet:convert(ConvertedHsl, #srgb{}),

		H_diff = abs(normalize_hue_diff(ConvertedHsl#hsl.h - ExpectedHsl#hsl.h)),
		S_diff = abs(ConvertedHsl#hsl.s - ExpectedHsl#hsl.s),
		L_diff = abs(ConvertedHsl#hsl.l - ExpectedHsl#hsl.l),

		R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
		G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
		B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

		Tol = 0.001,
		TolHue = 0.1,
		TolRGB = Tol,

		case {H_diff < TolHue, S_diff < Tol, L_diff < Tol, R_diff < TolRGB, G_diff < TolRGB, B_diff < TolRGB} of
			{true, true, true, true, true, true} ->
				ok;
			_ ->
				io:format("~n=== Падение теста srgb_to_hsl_roundtrip на '~s' ===~n"
				"Вход sRGB:      ~p~n"
				"Ожидаемый HSL:  ~p~n"
				"Полученный HSL: ~p~n"
				"Разница H/S/L:  ~.4f / ~.6f / ~.6f~n"
				"Back sRGB:      ~p~n"
				"ΔR/G/B:         ~.6f / ~.6f / ~.6f (должно < ~.4f)~n~n",
					[Name, Srgb, ExpectedHsl, ConvertedHsl, H_diff, S_diff, L_diff, BackSrgb, R_diff, G_diff, B_diff, TolRGB]),
				?assert(false)
		end
	end.


srgb_to_hsi_roundtrip_test_() ->
	[srgb_to_hsi_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.hsi =/= undefined].

srgb_to_hsi_roundtrip_case(#color_etalon{name = Name, srgb = Srgb, hsi = ExpectedHsi}) ->
	fun() ->
		ConvertedHsi = cbet:convert(Srgb, #hsi{illum = ?ILLUM_D65}),
		BackSrgb = cbet:convert(ConvertedHsi, #srgb{}),

		H_diff = abs(normalize_hue_diff(ConvertedHsi#hsi.h - ExpectedHsi#hsi.h)),
		S_diff = abs(ConvertedHsi#hsi.s - ExpectedHsi#hsi.s),
		I_diff = abs(ConvertedHsi#hsi.i - ExpectedHsi#hsi.i),

		R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
		G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
		B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

		Tol = 0.001,
		TolHue = 2.0,
		TolSI = 0.03,
		TolRGB = 0.005,

		case {H_diff < TolHue, S_diff < TolSI, I_diff < Tol, R_diff < TolRGB, G_diff < TolRGB, B_diff < TolRGB} of
			{true, true, true, true, true, true} ->
				ok;
			_ ->
				io:format("~n=== Падение теста srgb_to_hsi_roundtrip на '~s' ===~n"
				"Вход sRGB:      ~p~n"
				"Ожидаемый HSI:  ~p~n"
				"Полученный HSI: ~p~n"
				"Разница H/S/I:  ~.4f / ~.6f / ~.6f~n"
				"Back sRGB:      ~p~n"
				"ΔR/G/B:         ~.6f / ~.6f / ~.6f (должно < ~.4f)~n~n",
					[Name, Srgb, ExpectedHsi, ConvertedHsi, H_diff, S_diff, I_diff, BackSrgb, R_diff, G_diff, B_diff, TolRGB]),
				?assert(false)
		end
	end.


srgb_to_xyz65_roundtrip_test_() ->
	[srgb_to_xyz65_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.xyzd65 =/= undefined].

srgb_to_xyz50_roundtrip_test_() ->
	[srgb_to_xyz50_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.xyzd50 =/= undefined].


srgb_to_xyz65_roundtrip_case(
	#color_etalon{name = Name, srgb = Srgb, xyzd65 = ExpectedXyz}
) ->
	fun() ->
		ConvertedXyz = cbet:convert(Srgb, #xyz{illum = ?ILLUM_D65}),
		BackSrgb = cbet:convert(ConvertedXyz, #srgb{}),

		X_diff = abs(ConvertedXyz#xyz.x - ExpectedXyz#xyz.x),
		Y_diff = abs(ConvertedXyz#xyz.y - ExpectedXyz#xyz.y),
		Z_diff = abs(ConvertedXyz#xyz.z - ExpectedXyz#xyz.z),

		R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
		G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
		B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

		TolXYZ = 0.01,     %% XYZ в масштабе 0–100
		TolRGB = 0.001,

		case {X_diff < TolXYZ, Y_diff < TolXYZ, Z_diff < TolXYZ,
			R_diff < TolRGB, G_diff < TolRGB, B_diff < TolRGB} of
			{true, true, true, true, true, true} ->
				ok;
			_ ->
				io:format(
					"~n=== Падение теста srgb_to_xyz65_roundtrip на '~s' ===~n"
					"Вход sRGB:       ~p~n"
					"Ожидаемый XYZ65: ~p~n"
					"Полученный XYZ:  ~p~n"
					"ΔX/Y/Z:          ~.6f / ~.6f / ~.6f (должно < ~.4f)~n"
					"Back sRGB:       ~p~n"
					"ΔR/G/B:          ~.6f / ~.6f / ~.6f (должно < ~.4f)~n~n",
					[Name, Srgb, ExpectedXyz, ConvertedXyz,
						X_diff, Y_diff, Z_diff, TolXYZ,
						BackSrgb, R_diff, G_diff, B_diff, TolRGB]),
				?assert(false)
		end
	end.


srgb_to_xyz50_roundtrip_case(
	#color_etalon{name = Name, srgb = Srgb, xyzd50 = ExpectedXyz}
) ->
	fun() ->
		ConvertedXyz = cbet:convert(Srgb, #xyz{illum = ?ILLUM_D50}),
		BackSrgb = cbet:convert(ConvertedXyz, #srgb{}),

		X_diff = abs(ConvertedXyz#xyz.x - ExpectedXyz#xyz.x),
		Y_diff = abs(ConvertedXyz#xyz.y - ExpectedXyz#xyz.y),
		Z_diff = abs(ConvertedXyz#xyz.z - ExpectedXyz#xyz.z),

		R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
		G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
		B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

		TolXYZ = 0.02,   %% чуть больше из-за Bradford
		TolRGB = 0.001,

		case {X_diff < TolXYZ, Y_diff < TolXYZ, Z_diff < TolXYZ,
			R_diff < TolRGB, G_diff < TolRGB, B_diff < TolRGB} of
			{true, true, true, true, true, true} ->
				ok;
			_ ->
				io:format(
					"~n=== Падение теста srgb_to_xyz50_roundtrip на '~s' ===~n"
					"Вход sRGB:       ~p~n"
					"Ожидаемый XYZ50: ~p~n"
					"Полученный XYZ:  ~p~n"
					"ΔX/Y/Z:          ~.6f / ~.6f / ~.6f (должно < ~.4f)~n"
					"Back sRGB:       ~p~n"
					"ΔR/G/B:          ~.6f / ~.6f / ~.6f (должно < ~.4f)~n~n",
					[Name, Srgb, ExpectedXyz, ConvertedXyz,
						X_diff, Y_diff, Z_diff, TolXYZ,
						BackSrgb, R_diff, G_diff, B_diff, TolRGB]),
				?assert(false)
		end
	end.

srgb_to_labd65_roundtrip_test_() ->
	[srgb_to_labd65_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.lab_d65 =/= undefined].

srgb_to_luvd65_roundtrip_test_() ->
	[srgb_to_luvd65_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.luv_d65 =/= undefined].

srgb_to_labd50_roundtrip_test_() ->
	[srgb_to_labd50_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.lab_d50 =/= undefined].

srgb_to_luvd50_roundtrip_test_() ->
	[srgb_to_luvd50_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.luv_d50 =/= undefined].


%% -------------------- Lab D65 --------------------
srgb_to_labd65_roundtrip_case(#color_etalon{
	name = Name,
	srgb = Srgb,
	lab_d65 = ExpectedLab
}) ->
	fun() ->
		ConvertedLab = cbet:convert(Srgb, #lab{illum = ?ILLUM_D65}),
		BackSrgb = cbet:convert(ConvertedLab, #srgb{}),

		L_diff = abs(ConvertedLab#lab.l - ExpectedLab#lab.l),
		A_diff = abs(ConvertedLab#lab.a - ExpectedLab#lab.a),
		Blab_diff = abs(ConvertedLab#lab.b - ExpectedLab#lab.b),

		R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
		G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
		Brgb_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

		TolLab = 0.02,
		TolRGB = 0.005,

		case {L_diff < TolLab, A_diff < TolLab, Blab_diff < TolLab,
			R_diff < TolRGB, G_diff < TolRGB, Brgb_diff < TolRGB} of
			{true, true, true, true, true, true} ->
				ok;
			_ ->
				io:format("~n=== Падение теста sRGB<->Lab D65 на '~s' ===~n"
				"Вход sRGB:      ~p~n"
				"Ожидаемый Lab:  ~p~n"
				"Полученный Lab: ~p~n"
				"Разница L/A/B:  ~.4f / ~.4f / ~.4f~n"
				"Back sRGB:      ~p~n"
				"ΔR/G/B:         ~.6f / ~.6f / ~.6f (должно < ~.4f)~n~n",
					[Name, Srgb, ExpectedLab, ConvertedLab,
						L_diff, A_diff, Blab_diff, BackSrgb,
						R_diff, G_diff, Brgb_diff, TolRGB]),
				?assert(false)
		end
	end.

%% -------------------- Luv D65 --------------------
srgb_to_luvd65_roundtrip_case(#color_etalon{
	name = Name,
	srgb = Srgb,
	luv_d65 = ExpectedLuv
}) ->
	fun() ->
		ConvertedLuv = cbet:convert(Srgb, #luv{illum = ?ILLUM_D65}),
		BackSrgb = cbet:convert(ConvertedLuv, #srgb{}),

		L_diff = abs(ConvertedLuv#luv.l - ExpectedLuv#luv.l),
		U_diff = abs(ConvertedLuv#luv.u - ExpectedLuv#luv.u),
		V_diff = abs(ConvertedLuv#luv.v - ExpectedLuv#luv.v),

		R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
		G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
		B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

		TolLuv = 0.05,
		TolRGB = 0.005,

		case {L_diff < TolLuv, U_diff < TolLuv, V_diff < TolLuv,
			R_diff < TolRGB, G_diff < TolRGB, B_diff < TolRGB} of
			{true, true, true, true, true, true} ->
				ok;
			_ ->
				io:format("~n=== Падение теста sRGB<->Luv D65 на '~s' ===~n"
				"Вход sRGB:      ~p~n"
				"Ожидаемый Luv:  ~p~n"
				"Полученный Luv: ~p~n"
				"Разница L/U/V:  ~.4f / ~.4f / ~.4f~n"
				"Back sRGB:      ~p~n"
				"ΔR/G/B:         ~.6f / ~.6f / ~.6f (должно < ~.4f)~n~n",
					[Name, Srgb, ExpectedLuv, ConvertedLuv,
						L_diff, U_diff, V_diff, BackSrgb,
						R_diff, G_diff, B_diff, TolRGB]),
				?assert(false)
		end
	end.

%% -------------------- Lab D50 --------------------
srgb_to_labd50_roundtrip_case(#color_etalon{
	name = Name,
	srgb = Srgb,
	lab_d50 = ExpectedLab
}) ->
	fun() ->
		ConvertedLab = cbet:convert(Srgb, #lab{illum = ?ILLUM_D50}),
		BackSrgb = cbet:convert(ConvertedLab, #srgb{}),

		L_diff = abs(ConvertedLab#lab.l - ExpectedLab#lab.l),
		A_diff = abs(ConvertedLab#lab.a - ExpectedLab#lab.a),
		Blab_diff = abs(ConvertedLab#lab.b - ExpectedLab#lab.b),

		R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
		G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
		Brgb_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

		TolLab = 0.2,
		TolRGB = 0.005,

		case {L_diff < TolLab, A_diff < TolLab, Blab_diff < TolLab,
			R_diff < TolRGB, G_diff < TolRGB, Brgb_diff < TolRGB} of
			{true, true, true, true, true, true} ->
				ok;
			_ ->
				io:format("~n=== Падение теста sRGB<->Lab D50 на '~s' ===~n"
				"Вход sRGB:      ~p~n"
				"Ожидаемый Lab:  ~p~n"
				"Полученный Lab: ~p~n"
				"Разница L/A/B:  ~.4f / ~.4f / ~.4f~n"
				"Back sRGB:      ~p~n"
				"ΔR/G/B:         ~.6f / ~.6f / ~.6f (должно < ~.4f)~n~n",
					[Name, Srgb, ExpectedLab, ConvertedLab,
						L_diff, A_diff, Blab_diff, BackSrgb,
						R_diff, G_diff, Brgb_diff, TolRGB]),
				?assert(false)
		end
	end.

%% -------------------- Luv D50 --------------------
srgb_to_luvd50_roundtrip_case(#color_etalon{
	name = Name,
	srgb = Srgb,
	luv_d50 = ExpectedLuv
}) ->
	fun() ->
		ConvertedLuv = cbet:convert(Srgb, #luv{illum = ?ILLUM_D50}),
		BackSrgb = cbet:convert(ConvertedLuv, #srgb{}),

		L_diff = abs(ConvertedLuv#luv.l - ExpectedLuv#luv.l),
		U_diff = abs(ConvertedLuv#luv.u - ExpectedLuv#luv.u),
		V_diff = abs(ConvertedLuv#luv.v - ExpectedLuv#luv.v),

		R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
		G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
		B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

		TolLuv = 0.2,
		TolRGB = 0.005,

		case {L_diff < TolLuv, U_diff < TolLuv, V_diff < TolLuv,
			R_diff < TolRGB, G_diff < TolRGB, B_diff < TolRGB} of
			{true, true, true, true, true, true} ->
				ok;
			_ ->
				io:format("~n=== Падение теста sRGB<->Luv D50 на '~s' ===~n"
				"Вход sRGB:      ~p~n"
				"Ожидаемый Luv:  ~p~n"
				"Полученный Luv: ~p~n"
				"Разница L/U/V:  ~.4f / ~.4f / ~.4f~n"
				"Back sRGB:      ~p~n"
				"ΔR/G/B:         ~.6f / ~.6f / ~.6f (должно < ~.4f)~n~n",
					[Name, Srgb, ExpectedLuv, ConvertedLuv,
						L_diff, U_diff, V_diff, BackSrgb,
						R_diff, G_diff, B_diff, TolRGB]),
				?assert(false)
		end
	end.


%% ==================== CMY roundtrip ====================
srgb_to_cmy_roundtrip_test_() ->
	[srgb_to_cmy_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.cmy =/= undefined].

srgb_to_cmy_roundtrip_case(#color_etalon{name = Name, srgb = Srgb, cmy = ExpectedCmy}) ->
	fun() ->
		ConvertedCmy = cbet:convert(Srgb, #cmy{illum = ?ILLUM_D65}),
		BackSrgb = cbet:convert(ConvertedCmy, #srgb{}),

		C_diff = abs(ConvertedCmy#cmy.c - ExpectedCmy#cmy.c),
		M_diff = abs(ConvertedCmy#cmy.m - ExpectedCmy#cmy.m),
		Y_diff = abs(ConvertedCmy#cmy.y - ExpectedCmy#cmy.y),

		R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
		G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
		B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

		TolCMY = 0.002,
		TolRGB = 0.002,

		case {C_diff < TolCMY, M_diff < TolCMY, Y_diff < TolCMY,
			R_diff < TolRGB, G_diff < TolRGB, B_diff < TolRGB} of
			{true, true, true, true, true, true} ->
				ok;
			_ ->
				io:format("~n=== Падение теста srgb_to_cmy_roundtrip на '~s' ===~n"
				"Вход sRGB: ~p~n"
				"Ожидаемый CMY: ~p~n"
				"Полученный CMY: ~p~n"
				"Разница C/M/Y: ~.10f / ~.10f / ~.10f~n"
				"Back sRGB: ~p~n"
				"ΔR/G/B: ~.10f / ~.10f / ~.10f (должно < ~.2e)~n~n",
					[Name, Srgb, ExpectedCmy, ConvertedCmy,
						C_diff, M_diff, Y_diff,
						BackSrgb, R_diff, G_diff, B_diff, TolRGB]),
				?assert(false)
		end
	end.

%% ==================== Adobe RGB roundtrip ====================
srgb_to_adobe_rgb_roundtrip_test_() ->
	[srgb_to_adobe_rgb_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.adobe_rgb =/= undefined].

srgb_to_adobe_rgb_roundtrip_case(#color_etalon{name = Name, srgb = Srgb, adobe_rgb = ExpectedAdobe}) ->
	fun() ->
		Converted = cbet:convert(Srgb, #adobe_rgb{illum = ?ILLUM_D65}),
		BackSrgb = cbet:convert(Converted, #srgb{}),

		R_diff = abs(Converted#adobe_rgb.r - ExpectedAdobe#adobe_rgb.r),
		G_diff = abs(Converted#adobe_rgb.g - ExpectedAdobe#adobe_rgb.g),
		B_diff = abs(Converted#adobe_rgb.b - ExpectedAdobe#adobe_rgb.b),

		BackR = abs(BackSrgb#srgb.r - Srgb#srgb.r),
		BackG = abs(BackSrgb#srgb.g - Srgb#srgb.g),
		BackB = abs(BackSrgb#srgb.b - Srgb#srgb.b),

		Tol = 0.002,   % чуть больше, чем для HSV/HSL, из-за матричных погрешностей

		case {R_diff < Tol, G_diff < Tol, B_diff < Tol, BackR < Tol, BackG < Tol, BackB < Tol} of
			{true, true, true, true, true, true} -> ok;
			_ ->
				io:format("~n=== FAIL srgb <-> adobe_rgb roundtrip '~s' ===~n"
				"sRGB:      ~p~n"
				"Expected Adobe: ~p~n"
				"Got Adobe:      ~p~n"
				"ΔR/G/B Adobe:   ~.6f / ~.6f / ~.6f~n"
				"Back sRGB:      ~p~n"
				"ΔR/G/B back:    ~.6f / ~.6f / ~.6f~n~n",
					[Name, Srgb, ExpectedAdobe, Converted, R_diff, G_diff, B_diff, BackSrgb, BackR, BackG, BackB]),
				?assert(false)
		end
	end.


%% ==================== Adobe RGB out of gamut for SRGB ====================
adobe_rgb_to_srgb_out_of_gamut_test_() ->
	[adobe_rgb_to_srgb_out_of_gamut_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.adobe_rgb_out_of_gamut =/= undefined].

adobe_rgb_to_srgb_out_of_gamut_case(#color_etalon{name = Name, srgb = ExpectedSrgbNoClamp, adobe_rgb_out_of_gamut = Argb}) ->
	fun() ->
		ExpectedSrgbClamp = ExpectedSrgbNoClamp#srgb{
			r = max(ExpectedSrgbNoClamp#srgb.r, 0.0),
			g = max(ExpectedSrgbNoClamp#srgb.g, 0.0),
			b = max(ExpectedSrgbNoClamp#srgb.b, 0.0)
		},

		ConvertedClamp = cbet:convert(Argb, #srgb{illum = ?ILLUM_D65}, #{clamp => true}),
		ConvertedNoClamp = cbet:convert(Argb, #srgb{illum = ?ILLUM_D65}, #{clamp => false}),

		RNoClamp_diff = abs(ConvertedNoClamp#srgb.r - ExpectedSrgbNoClamp#srgb.r),
		GNoClamp_diff = abs(ConvertedNoClamp#srgb.g - ExpectedSrgbNoClamp#srgb.g),
		BNoClamp_diff = abs(ConvertedNoClamp#srgb.b - ExpectedSrgbNoClamp#srgb.b),

		RClamp_diff = abs(ConvertedClamp#srgb.r - ExpectedSrgbClamp#srgb.r),
		GClamp_diff = abs(ConvertedClamp#srgb.g - ExpectedSrgbClamp#srgb.g),
		BClamp_diff = abs(ConvertedClamp#srgb.b - ExpectedSrgbClamp#srgb.b),


		Tol = 0.02,

		case {RNoClamp_diff < Tol, GNoClamp_diff < Tol, BNoClamp_diff < Tol,
			RClamp_diff < Tol, GClamp_diff < Tol, BClamp_diff < Tol} of
			{true, true, true, true, true, true} -> ok;
			_ ->
				io:format("~n=== FAIL adobe_rgb -> srgb (out of gamut) '~s' ===~n"
				"ARGB:      ~p~n"
				"Expected SRGB (no clamp): ~p~n"
				"Got SRGB (no clamp):      ~p~n"
				"Expected SRGB (clamp): ~p~n"
				"Got SRGB (clamp):      ~p~n",
					[Name, Argb, ExpectedSrgbNoClamp, ConvertedNoClamp,
						ExpectedSrgbClamp, ConvertedClamp]),
				?assert(false)
		end
	end.


%% ==================== Display P3 roundtrip ====================
srgb_to_display_p3_roundtrip_test_() ->
	[srgb_to_display_p3_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.display_p3 =/= undefined].

srgb_to_display_p3_roundtrip_case(#color_etalon{name = Name, srgb = Srgb, display_p3 = ExpectedP3}) ->
	fun() ->
		Converted = cbet:convert(Srgb, #display_p3{illum = ?ILLUM_D65}),
		BackSrgb = cbet:convert(Converted, #srgb{}),

		R_diff = abs(Converted#display_p3.r - ExpectedP3#display_p3.r),
		G_diff = abs(Converted#display_p3.g - ExpectedP3#display_p3.g),
		B_diff = abs(Converted#display_p3.b - ExpectedP3#display_p3.b),

		BackR = abs(BackSrgb#srgb.r - Srgb#srgb.r),
		BackG = abs(BackSrgb#srgb.g - Srgb#srgb.g),
		BackB = abs(BackSrgb#srgb.b - Srgb#srgb.b),

		Tol = 0.02,

		case {R_diff < Tol, G_diff < Tol, B_diff < Tol, BackR < Tol, BackG < Tol, BackB < Tol} of
			{true, true, true, true, true, true} -> ok;
			_ ->
				io:format("~n=== FAIL srgb <-> display_p3 roundtrip '~s' ===~n"
				"sRGB:      ~p~n"
				"Expected P3: ~p~n"
				"Got P3:      ~p~n"
				"ΔR/G/B P3:   ~.6f / ~.6f / ~.6f~n"
				"Back sRGB:   ~p~n"
				"ΔR/G/B back: ~.6f / ~.6f / ~.6f~n~n",
					[Name, Srgb, ExpectedP3, Converted, R_diff, G_diff, B_diff, BackSrgb, BackR, BackG, BackB]),
				?assert(false)
		end
	end.

%% ==================== Rec.2020 roundtrip ====================
srgb_to_rec2020_roundtrip_test_() ->
    [srgb_to_rec2020_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.rec2020 =/= undefined].


srgb_to_rec2020_roundtrip_case(#color_etalon{name=Name, srgb=Srgb, rec2020=ExpectedRec2020}) ->
    fun() ->
        Converted = cbet:convert(Srgb, #rec2020{illum=?ILLUM_D65}),
        BackSrgb = cbet:convert(Converted, #srgb{}),

        R_diff = abs(Converted#rec2020.r - ExpectedRec2020#rec2020.r),
        G_diff = abs(Converted#rec2020.g - ExpectedRec2020#rec2020.g),
        B_diff = abs(Converted#rec2020.b - ExpectedRec2020#rec2020.b),

        BackR_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
        BackG_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
        BackB_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

        TolConverted = 0.008,
        TolBack      = 0.004,

        case {R_diff     < TolConverted,
              G_diff     < TolConverted,
              B_diff     < TolConverted,
              BackR_diff < TolBack,
              BackG_diff < TolBack,
              BackB_diff < TolBack} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL srgb <-> rec2020 roundtrip '~s' ===~n"
                    "Вход sRGB:        ~p~n"
                    "Ожидаемый Rec2020: ~p~n"
                    "Полученный Rec2020:~p~n"
                    "ΔR/G/B в Rec2020:  ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n"
                    "Обратно sRGB:      ~p~n"
                    "ΔR/G/B обратно:    ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n~n",
                    [Name, Srgb, ExpectedRec2020, Converted,
                     R_diff, G_diff, B_diff, TolConverted,
                     BackSrgb, BackR_diff, BackG_diff, BackB_diff, TolBack]
                ),
                ?assert(false)
        end
    end.

%% ==================== Rec.709 roundtrip ====================
srgb_to_rec709_roundtrip_test_() ->
    [srgb_to_rec709_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.rec709 =/= undefined].


srgb_to_rec709_roundtrip_case(#color_etalon{name=Name, srgb=Srgb, rec709=ExpectedRec709}) ->
    fun() ->
        Converted = cbet:convert(Srgb, #rec709{illum=?ILLUM_D65}),
        BackSrgb = cbet:convert(Converted, #srgb{}),

        R_diff = abs(Converted#rec709.r - ExpectedRec709#rec709.r),
        G_diff = abs(Converted#rec709.g - ExpectedRec709#rec709.g),
        B_diff = abs(Converted#rec709.b - ExpectedRec709#rec709.b),

        BackR_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
        BackG_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
        BackB_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

        TolConverted = 0.0015,
        TolBack      = 0.0005,

        case {R_diff     < TolConverted,
              G_diff     < TolConverted,
              B_diff     < TolConverted,
              BackR_diff < TolBack,
              BackG_diff < TolBack,
              BackB_diff < TolBack} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL srgb <-> rec709 roundtrip '~s' ===~n"
                    "Вход sRGB:         ~p~n"
                    "Ожидаемый Rec.709:  ~p~n"
                    "Полученный Rec.709: ~p~n"
                    "ΔR/G/B в Rec.709:   ~.7f / ~.7f / ~.7f  (допуск ~.4f)~n"
                    "Обратно sRGB:       ~p~n"
                    "ΔR/G/B обратно:     ~.7f / ~.7f / ~.7f  (допуск ~.4f)~n~n",
                    [Name, Srgb, ExpectedRec709, Converted,
                     R_diff, G_diff, B_diff, TolConverted,
                     BackSrgb, BackR_diff, BackG_diff, BackB_diff, TolBack]
                ),
                ?assert(false)
        end
    end.


% ==================== ProPhoto RGB roundtrip ====================
srgb_to_prophoto_rgb_roundtrip_test_() ->
    [srgb_to_prophoto_rgb_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.prophoto_rgb =/= undefined].


srgb_to_prophoto_rgb_roundtrip_case(#color_etalon{name=Name, srgb=Srgb, prophoto_rgb=ExpectedProPhoto}) ->
    fun() ->
        Converted = cbet:convert(Srgb, #prophoto_rgb{illum=?ILLUM_D50}),
        BackSrgb = cbet:convert(Converted, #srgb{}),

        R_diff = abs(Converted#prophoto_rgb.r - ExpectedProPhoto#prophoto_rgb.r),
        G_diff = abs(Converted#prophoto_rgb.g - ExpectedProPhoto#prophoto_rgb.g),
        B_diff = abs(Converted#prophoto_rgb.b - ExpectedProPhoto#prophoto_rgb.b),

        BackR_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
        BackG_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
        BackB_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

        TolConverted = 0.002,
        TolBack      = 0.002,

        case {R_diff     < TolConverted,
              G_diff     < TolConverted,
              B_diff     < TolConverted,
              BackR_diff < TolBack,
              BackG_diff < TolBack,
              BackB_diff < TolBack} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL srgb <-> prophoto_rgb roundtrip '~s' ===~n"
                    "Вход sRGB:              ~p~n"
                    "Ожидаемый ProPhoto RGB: ~p~n"
                    "Полученный ProPhoto RGB:~p~n"
                    "ΔR/G/B в ProPhoto:      ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n"
                    "Обратно sRGB:           ~p~n"
                    "ΔR/G/B обратно:         ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n~n",
                    [Name, Srgb, ExpectedProPhoto, Converted,
                     R_diff, G_diff, B_diff, TolConverted,
                     BackSrgb, BackR_diff, BackG_diff, BackB_diff, TolBack]
                ),
                ?assert(false)
        end
    end.


%% ==================== Wide Gamut RGB roundtrip ====================
srgb_to_wide_gamut_rgb_roundtrip_test_() ->
    [srgb_to_wide_gamut_rgb_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.wide_gamut_rgb =/= undefined].


srgb_to_wide_gamut_rgb_roundtrip_case(#color_etalon{name=Name, srgb=Srgb, wide_gamut_rgb=ExpectedWideGamut}) ->
    fun() ->
        Converted = cbet:convert(Srgb, #wide_gamut_rgb{illum=?ILLUM_D50}),
        BackSrgb = cbet:convert(Converted, #srgb{}),

        R_diff = abs(Converted#wide_gamut_rgb.r - ExpectedWideGamut#wide_gamut_rgb.r),
        G_diff = abs(Converted#wide_gamut_rgb.g - ExpectedWideGamut#wide_gamut_rgb.g),
        B_diff = abs(Converted#wide_gamut_rgb.b - ExpectedWideGamut#wide_gamut_rgb.b),

        BackR_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
        BackG_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
        BackB_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

        TolConverted = 0.002,
        TolBack      = 0.002,

        case {R_diff     < TolConverted,
              G_diff     < TolConverted,
              B_diff     < TolConverted,
              BackR_diff < TolBack,
              BackG_diff < TolBack,
              BackB_diff < TolBack} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL srgb <-> wide_gamut_rgb roundtrip '~s' ===~n"
                    "Вход sRGB:                 ~p~n"
                    "Ожидаемый Wide Gamut RGB:  ~p~n"
                    "Полученный Wide Gamut RGB: ~p~n"
                    "ΔR/G/B в Wide Gamut:       ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n"
                    "Обратно sRGB:              ~p~n"
                    "ΔR/G/B обратно:            ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n~n",
                    [Name, Srgb, ExpectedWideGamut, Converted,
                     R_diff, G_diff, B_diff, TolConverted,
                     BackSrgb, BackR_diff, BackG_diff, BackB_diff, TolBack]
                ),
                ?assert(false)
        end
    end.

%% ==================== HWB roundtrip ====================
srgb_to_hwb_roundtrip_test_() ->
    [srgb_to_hwb_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.hwb =/= undefined].


srgb_to_hwb_roundtrip_case(#color_etalon{name=Name, srgb=Srgb, hwb=ExpectedHwb}) ->
    fun() ->
        ConvertedHwb = cbet:convert(Srgb, #hwb{illum=?ILLUM_D65}),
        BackSrgb = cbet:convert(ConvertedHwb, #srgb{}),

        H_diff = abs(normalize_hue_diff(ConvertedHwb#hwb.h - ExpectedHwb#hwb.h)),
        W_diff = abs(ConvertedHwb#hwb.w - ExpectedHwb#hwb.w),
        B_diff = abs(ConvertedHwb#hwb.b - ExpectedHwb#hwb.b),

        R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
        G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
        B_rgb_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

        TolHue   = 0.2,
        TolWB    = 0.001,
        TolRGB   = 0.0005,

        case {H_diff  < TolHue,
              W_diff  < TolWB,
              B_diff  < TolWB,
              R_diff  < TolRGB,
              G_diff  < TolRGB,
              B_rgb_diff < TolRGB} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL srgb <-> hwb roundtrip '~s' ===~n"
                    "Вход sRGB:        ~p~n"
                    "Ожидаемый HWB:    ~p~n"
                    "Полученный HWB:   ~p~n"
                    "ΔH / ΔW / ΔB:     ~.4f / ~.6f / ~.6f~n"
                    "Обратно sRGB:     ~p~n"
                    "ΔR / ΔG / ΔB:     ~.7f / ~.7f / ~.7f  (допуск ~.4f)~n~n",
                    [Name, Srgb, ExpectedHwb, ConvertedHwb,
                     H_diff, W_diff, B_diff,
                     BackSrgb, R_diff, G_diff, B_rgb_diff, TolRGB]
                ),
                ?assert(false)
        end
    end.

%% ==================== IPT roundtrip ====================
srgb_to_ipt_roundtrip_test_() ->
    [srgb_to_ipt_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.ipt =/= undefined].


srgb_to_ipt_roundtrip_case(#color_etalon{name=Name, srgb=Srgb, ipt=ExpectedIpt}) ->
    fun() ->
        ConvertedIpt = cbet:convert(Srgb, #ipt{illum=?ILLUM_D65}),
        BackSrgb = cbet:convert(ConvertedIpt, #srgb{}),

        I_diff = abs(ConvertedIpt#ipt.i - ExpectedIpt#ipt.i),
        P_diff = abs(ConvertedIpt#ipt.p - ExpectedIpt#ipt.p),
        T_diff = abs(ConvertedIpt#ipt.t - ExpectedIpt#ipt.t),

        R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
        G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
        B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

        TolIPT   = 0.008,     % типичный допуск для I/P/T (может быть 0.005–0.015)
        TolRGB   = 0.003,

        case {I_diff < TolIPT,
              P_diff < TolIPT,
              T_diff < TolIPT,
              R_diff < TolRGB,
              G_diff < TolRGB,
              B_diff < TolRGB} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL srgb <-> ipt roundtrip '~s' ===~n"
                    "Вход sRGB:      ~p~n"
                    "Ожидаемый IPT:  ~p~n"
                    "Полученный IPT: ~p~n"
                    "ΔI / ΔP / ΔT:   ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n"
                    "Обратно sRGB:   ~p~n"
                    "ΔR / ΔG / ΔB:   ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n~n",
                    [Name, Srgb, ExpectedIpt, ConvertedIpt,
                     I_diff, P_diff, T_diff, TolIPT,
                     BackSrgb, R_diff, G_diff, B_diff, TolRGB]
                ),
                ?assert(false)
        end
    end.


%% ==================== CIE xyY roundtrip ====================
srgb_to_xyy_roundtrip_test_() ->
    [srgb_to_xyy_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.xyy =/= undefined, Etalon#color_etalon.adobe_rgb_out_of_gamut == undefined].

adobe_rgb_out_of_gamut_to_xyy_roundtrip_test_() ->
    [adobe_rgb_out_of_gamut_to_xyy_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.adobe_rgb_out_of_gamut =/= undefined, Etalon#color_etalon.xyy =/= undefined].


srgb_to_xyy_roundtrip_case(#color_etalon{name=Name, srgb=Srgb, xyy=ExpectedXyy}) ->
    fun() ->
        ConvertedXyy = cbet:convert(Srgb, #xyy{illum=?ILLUM_D65}),
        BackSrgb = cbet:convert(ConvertedXyy, #srgb{}),

        X_diff     = abs(ConvertedXyy#xyy.x         - ExpectedXyy#xyy.x),
        Y_diff     = abs(ConvertedXyy#xyy.y         - ExpectedXyy#xyy.y),
        Lum_diff   = abs(ConvertedXyy#xyy.luminance - ExpectedXyy#xyy.luminance),

        R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
        G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
        B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

        TolXY        = 0.002,
        TolLuminance = 0.7,


        TolRGB       = 0.001,

        case {X_diff     < TolXY,
              Y_diff     < TolXY,
              Lum_diff   < TolLuminance,
              R_diff     < TolRGB,
              G_diff     < TolRGB,
              B_diff     < TolRGB} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL srgb <-> xyy roundtrip '~s' ===~n"
                    "Вход sRGB:         ~p~n"
                    "Ожидаемый xyY:     ~p~n"
                    "Полученный xyY:    ~p~n"
                    "Δx     = ~.6f~n"
                    "Δy     = ~.6f~n"
                    "ΔY/lum = ~.6f   (допуск ~.4f)~n"
                    "Обратно sRGB:      ~p~n"
                    "ΔR / ΔG / ΔB = ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n~n",
                    [Name, Srgb, ExpectedXyy, ConvertedXyy,
                     X_diff, Y_diff, Lum_diff, TolLuminance,
                     BackSrgb, R_diff, G_diff, B_diff, TolRGB]
                ),
                ?assert(false)
        end
    end.


adobe_rgb_out_of_gamut_to_xyy_roundtrip_case(#color_etalon{name=Name, adobe_rgb_out_of_gamut = Argb, xyy=ExpectedXyy}) ->
    fun() ->
        ConvertedXyy = cbet:convert(Argb, #xyy{illum=?ILLUM_D65}),
        BackArgb = cbet:convert(ConvertedXyy, #adobe_rgb{}),

        X_diff     = abs(ConvertedXyy#xyy.x         - ExpectedXyy#xyy.x),
        Y_diff     = abs(ConvertedXyy#xyy.y         - ExpectedXyy#xyy.y),
        Lum_diff   = abs(ConvertedXyy#xyy.luminance - ExpectedXyy#xyy.luminance),

        R_diff = abs(BackArgb#adobe_rgb.r - Argb#adobe_rgb.r),
        G_diff = abs(BackArgb#adobe_rgb.g - Argb#adobe_rgb.g),
        B_diff = abs(BackArgb#adobe_rgb.b - Argb#adobe_rgb.b),

        TolXY        = 0.002,
        TolLuminance = 0.7,
        TolRGB       = 0.001,

        case {X_diff     < TolXY,
              Y_diff     < TolXY,
              Lum_diff   < TolLuminance,
              R_diff     < TolRGB,
              G_diff     < TolRGB,
              B_diff     < TolRGB} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL argb out of gamut for srgb <-> xyy roundtrip '~s' ===~n"
                    "Вход aRGB:         ~p~n"
                    "Ожидаемый xyY:     ~p~n"
                    "Полученный xyY:    ~p~n"
                    "Δx     = ~.6f~n"
                    "Δy     = ~.6f~n"
                    "ΔY/lum = ~.6f   (допуск ~.4f)~n"
                    "Обратно aRGB:      ~p~n"
                    "ΔR / ΔG / ΔB = ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n~n",
                    [Name, Argb, ExpectedXyy, ConvertedXyy,
                     X_diff, Y_diff, Lum_diff, TolLuminance,
                     BackArgb, R_diff, G_diff, B_diff, TolRGB]
                ),
                ?assert(false)
        end
    end.


%% ==================== LCHuv roundtrip ====================
srgb_to_lchuv_roundtrip_test_() ->
    [srgb_to_lchuv_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.lchuv =/= undefined].


srgb_to_lchuv_roundtrip_case(#color_etalon{name=Name, srgb=Srgb, lchuv=ExpectedLchuv}) ->
    fun() ->
        ConvertedLchuv = cbet:convert(Srgb, #lchuv{illum=?ILLUM_D50}),
        BackSrgb = cbet:convert(ConvertedLchuv, #srgb{}),

        L_diff = abs(ConvertedLchuv#lchuv.l - ExpectedLchuv#lchuv.l),
        C_diff = abs(ConvertedLchuv#lchuv.c - ExpectedLchuv#lchuv.c),
        H_diff = abs(normalize_hue_diff(ConvertedLchuv#lchuv.h - ExpectedLchuv#lchuv.h)),

        R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
        G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
        B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

        TolL       = 0.15,
        TolC       = 0.8,
        TolHue     = 0.6,
        TolRGB     = 0.004,

        case {L_diff < TolL,
              C_diff < TolC,
              H_diff < TolHue,
              R_diff < TolRGB,
              G_diff < TolRGB,
              B_diff < TolRGB} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL srgb <-> lchuv roundtrip '~s' ===~n"
                    "Вход sRGB:          ~p~n"
                    "Ожидаемый LChuv:    ~p~n"
                    "Полученный LChuv:   ~p~n"
                    "ΔL     = ~.4f~n"
                    "ΔC     = ~.4f~n"
                    "ΔH     = ~.4f   (hue diff после нормализации)~n"
                    "Обратно sRGB:       ~p~n"
                    "ΔR / ΔG / ΔB = ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n~n",
                    [Name, Srgb, ExpectedLchuv, ConvertedLchuv,
                     L_diff, C_diff, H_diff,
                     BackSrgb, R_diff, G_diff, B_diff, TolRGB]
                ),
                ?assert(false)
        end
    end.

%% ==================== LogLuv roundtrip ====================
srgb_to_logluv_roundtrip_test_() ->
    [srgb_to_logluv_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.logluv =/= undefined].


srgb_to_logluv_roundtrip_case(#color_etalon{name=Name, srgb=Srgb, logluv=ExpectedLogLuv}) ->
    fun() ->
        ConvertedLogLuv = cbet:convert(Srgb, #logluv{illum=?ILLUM_D65}),
        BackSrgb = cbet:convert(ConvertedLogLuv, #srgb{}),

        L_diff = abs(ConvertedLogLuv#logluv.l - ExpectedLogLuv#logluv.l),
        U_diff = abs(ConvertedLogLuv#logluv.u - ExpectedLogLuv#logluv.u),
        V_diff = abs(ConvertedLogLuv#logluv.v - ExpectedLogLuv#logluv.v),

        R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
        G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
        B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),


        TolL   = 0.15,
        TolUV  = 0.8,
        TolRGB = 0.004,

        case {L_diff < TolL,
              U_diff < TolUV,
              V_diff < TolUV,
              R_diff < TolRGB,
              G_diff < TolRGB,
              B_diff < TolRGB} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL srgb <-> logluv roundtrip '~s' ===~n"
                    "Вход sRGB:           ~p~n"
                    "Ожидаемый LogLuv:    ~p~n"
                    "Полученный LogLuv:   ~p~n"
                    "ΔL (log lum) = ~.6f~n"
                    "Δu           = ~.6f~n"
                    "Δv           = ~.6f~n"
                    "Обратно sRGB:        ~p~n"
                    "ΔR / ΔG / ΔB = ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n~n",
                    [Name, Srgb, ExpectedLogLuv, ConvertedLogLuv,
                     L_diff, U_diff, V_diff,
                     BackSrgb, R_diff, G_diff, B_diff, TolRGB]
                ),
                ?assert(false)
        end
    end.

%% ==================== DIN99d Lab roundtrip ====================
srgb_to_din99d_lab_roundtrip_test_() ->
    [srgb_to_din99d_lab_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.din99d_lab =/= undefined].


srgb_to_din99d_lab_roundtrip_case(#color_etalon{name=Name, srgb=Srgb, din99d_lab=ExpectedDin99d}) ->
    fun() ->
        % Важно: передаём variant явно, чтобы гарантировать DIN99d
        ConvertedDin99d = cbet:convert(Srgb, #din99_lab{illum=?ILLUM_D50, variant=?DIN99d}),
        BackSrgb = cbet:convert(ConvertedDin99d, #srgb{}),

        L_diff = abs(ConvertedDin99d#din99_lab.l - ExpectedDin99d#din99_lab.l),
        A_diff = abs(ConvertedDin99d#din99_lab.a - ExpectedDin99d#din99_lab.a),
        B_diff = abs(ConvertedDin99d#din99_lab.b - ExpectedDin99d#din99_lab.b),

        R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
        G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
        B_rgb_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),


        TolL   = 0.20,
        TolAB  = 1.00,
        TolRGB = 0.005,

        case {L_diff   < TolL,
              A_diff   < TolAB,
              B_diff   < TolAB,
              R_diff   < TolRGB,
              G_diff   < TolRGB,
              B_rgb_diff < TolRGB} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL srgb <-> din99d_lab roundtrip '~s' ===~n"
                    "Вход sRGB:           ~p~n"
                    "Ожидаемый DIN99d Lab:~p~n"
                    "Полученный DIN99d Lab:~p~n"
                    "ΔL     = ~.4f~n"
                    "Δa     = ~.4f~n"
                    "Δb     = ~.4f~n"
                    "Обратно sRGB:         ~p~n"
                    "ΔR / ΔG / ΔB = ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n~n",
                    [Name, Srgb, ExpectedDin99d, ConvertedDin99d,
                     L_diff, A_diff, B_diff,
                     BackSrgb, R_diff, G_diff, B_rgb_diff, TolRGB]
                ),
                ?assert(false)
        end
    end.

%% ==================== LCH roundtrip ====================
srgb_to_lch_roundtrip_test_() ->
    [srgb_to_lch_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.lch =/= undefined].


srgb_to_lch_roundtrip_case(#color_etalon{name=Name, srgb=Srgb, lch=ExpectedLch}) ->
    fun() ->
        ConvertedLch = cbet:convert(Srgb, #lch{illum=?ILLUM_D65}),
        BackSrgb = cbet:convert(ConvertedLch, #srgb{}),

        H_diff = abs(normalize_hue_diff(ConvertedLch#lch.h - ExpectedLch#lch.h)),
        C_diff = abs(ConvertedLch#lch.c - ExpectedLch#lch.c),
        L_diff = abs(ConvertedLch#lch.l - ExpectedLch#lch.l),

        R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
        G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
        B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),


        TolHue   = 0.5,
        TolC     = 0.8,
        TolL     = 0.15,
        TolRGB   = 0.004,

        case {H_diff < TolHue,
              C_diff < TolC,
              L_diff < TolL,
              R_diff < TolRGB,
              G_diff < TolRGB,
              B_diff < TolRGB} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL srgb <-> lch roundtrip '~s' ===~n"
                    "Вход sRGB:       ~p~n"
                    "Ожидаемый LCH:   ~p~n"
                    "Полученный LCH:  ~p~n"
                    "ΔH (hue) = ~.4f~n"
                    "ΔC (chroma) = ~.4f~n"
                    "ΔL (lightness) = ~.4f~n"
                    "Обратно sRGB:    ~p~n"
                    "ΔR / ΔG / ΔB = ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n~n",
                    [Name, Srgb, ExpectedLch, ConvertedLch,
                     H_diff, C_diff, L_diff,
                     BackSrgb, R_diff, G_diff, B_diff, TolRGB]
                ),
                ?assert(false)
        end
    end.


%% ==================== Oklab roundtrip ====================
srgb_to_oklab_roundtrip_test_() ->
    [srgb_to_oklab_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.oklab =/= undefined].


srgb_to_oklab_roundtrip_case(#color_etalon{name=Name, srgb=Srgb, oklab=ExpectedOklab}) ->
    fun() ->
        ConvertedOklab = cbet:convert(Srgb, #oklab{}),
        BackSrgb = cbet:convert(ConvertedOklab, #srgb{}),

        L_diff = abs(ConvertedOklab#oklab.l - ExpectedOklab#oklab.l),
        A_diff = abs(ConvertedOklab#oklab.a - ExpectedOklab#oklab.a),
        B_diff = abs(ConvertedOklab#oklab.b - ExpectedOklab#oklab.b),

        R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
        G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
        B_rgb_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

        % Oklab — очень равномерное пространство
        % round-trip обычно точный, но на очень насыщенных цветах может быть небольшая погрешность
        TolL   = 0.004,     % Lightness — очень точная
        TolAB  = 0.008,     % a и b — обычно лучше, чем в CIELAB
        TolRGB = 0.002,     % обратный round-trip в sRGB

        case {L_diff   < TolL,
              A_diff   < TolAB,
              B_diff   < TolAB,
              R_diff   < TolRGB,
              G_diff   < TolRGB,
              B_rgb_diff < TolRGB} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL srgb <-> oklab roundtrip '~s' ===~n"
                    "Вход sRGB:       ~p~n"
                    "Ожидаемый Oklab: ~p~n"
                    "Полученный Oklab:~p~n"
                    "ΔL = ~.6f~n"
                    "Δa = ~.6f~n"
                    "Δb = ~.6f~n"
                    "Обратно sRGB:    ~p~n"
                    "ΔR / ΔG / ΔB = ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n~n",
                    [Name, Srgb, ExpectedOklab, ConvertedOklab,
                     L_diff, A_diff, B_diff,
                     BackSrgb, R_diff, G_diff, B_rgb_diff, TolRGB]
                ),
                ?assert(false)
        end
    end.


%% ==================== Oklch roundtrip ====================
srgb_to_oklch_roundtrip_test_() ->
    [srgb_to_oklch_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.oklch =/= undefined].


srgb_to_oklch_roundtrip_case(#color_etalon{name=Name, srgb=Srgb, oklch=ExpectedOklch}) ->
    fun() ->
        ConvertedOklch = cbet:convert(Srgb, #oklch{}),
        BackSrgb = cbet:convert(ConvertedOklch, #srgb{}),

        L_diff = abs(ConvertedOklch#oklch.l - ExpectedOklch#oklch.l),
        C_diff = abs(ConvertedOklch#oklch.c - ExpectedOklch#oklch.c),
        H_diff = abs(normalize_hue_diff(ConvertedOklch#oklch.h - ExpectedOklch#oklch.h)),

        R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
        G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
        B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

        TolL   = 0.004,     % Lightness — очень точная
        TolC   = 0.012,     % Chroma — чуть больше погрешность, чем в Oklab a/b
        TolHue = 0.4,       % Hue — циклический, небольшая погрешность на границах
        TolRGB = 0.0025,    % обратный round-trip

        case {L_diff < TolL,
              C_diff < TolC,
              H_diff < TolHue,
              R_diff < TolRGB,
              G_diff < TolRGB,
              B_diff < TolRGB} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL srgb <-> oklch roundtrip '~s' ===~n"
                    "Вход sRGB:        ~p~n"
                    "Ожидаемый Oklch:  ~p~n"
                    "Полученный Oklch: ~p~n"
                    "ΔL = ~.6f~n"
                    "ΔC = ~.6f~n"
                    "ΔH = ~.4f  (hue diff после нормализации)~n"
                    "Обратно sRGB:     ~p~n"
                    "ΔR / ΔG / ΔB = ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n~n",
                    [Name, Srgb, ExpectedOklch, ConvertedOklch,
                     L_diff, C_diff, H_diff,
                     BackSrgb, R_diff, G_diff, B_diff, TolRGB]
                ),
                ?assert(false)
        end
    end.


%% ==================== ICtCp (PQ) roundtrip ====================
srgb_to_ictcp_pq_roundtrip_test_() ->
    [srgb_to_ictcp_pq_roundtrip_case(Etalon) || Etalon <- etalon_colors(), Etalon#color_etalon.ictcp_pq =/= undefined].


srgb_to_ictcp_pq_roundtrip_case(#color_etalon{name=Name, srgb=Srgb, ictcp_pq=ExpectedIctcp}) ->
    fun() ->
        % transfer = PQ
        ConvertedIctcp = cbet:convert(Srgb, #ictcp{illum=?ILLUM_D65, transfer=?TRANSFER_PQ}),
        BackSrgb = cbet:convert(ConvertedIctcp, #srgb{}),

        I_diff  = abs(ConvertedIctcp#ictcp.i  - ExpectedIctcp#ictcp.i),
        Ct_diff = abs(ConvertedIctcp#ictcp.ct - ExpectedIctcp#ictcp.ct),
        Cp_diff = abs(ConvertedIctcp#ictcp.cp - ExpectedIctcp#ictcp.cp),

        R_diff = abs(BackSrgb#srgb.r - Srgb#srgb.r),
        G_diff = abs(BackSrgb#srgb.g - Srgb#srgb.g),
        B_diff = abs(BackSrgb#srgb.b - Srgb#srgb.b),

        TolI     = 0.005,
        TolCtCp  = 0.012,
        TolRGB   = 0.004,

        case {I_diff  < TolI,
              Ct_diff < TolCtCp,
              Cp_diff < TolCtCp,
              R_diff  < TolRGB,
              G_diff  < TolRGB,
              B_diff  < TolRGB} of
            {true, true, true, true, true, true} ->
                ok;
            _ ->
                io:format(
                    "~n=== FAIL srgb <-> ictcp_pq roundtrip '~s' ===~n"
                    "Вход sRGB:           ~p~n"
                    "Ожидаемый ICtCp PQ:  ~p~n"
                    "Полученный ICtCp:    ~p~n"
                    "ΔI     = ~.6f~n"
                    "ΔCt    = ~.6f~n"
                    "ΔCp    = ~.6f~n"
                    "Обратно sRGB:        ~p~n"
                    "ΔR / ΔG / ΔB = ~.6f / ~.6f / ~.6f  (допуск ~.4f)~n~n",
                    [Name, Srgb, ExpectedIctcp, ConvertedIctcp,
                     I_diff, Ct_diff, Cp_diff,
                     BackSrgb, R_diff, G_diff, B_diff, TolRGB]
                ),
                ?assert(false)
        end
    end.


cam16_test() ->
	ExpectedResult = #cam16{j = 41.731, c = 0.1033557,
		h_angle = 217.067959, h_quad = 275.594986,
		m = 0.10743677, s = 2.345015,
		q = 195.3717, a = 23.93954594544513,
		b = -4.790725135415859e-4, d = 0.9944687800884374, f = 1.0,
		c_sur = 0.69, n_c = 1.0},

	Result = cbet:cam16_model({19.01, 20.00, 21.78}, {95.05, 100.00, 108.88}, 318.31, 20.0, #{surround => average, compute_H => true}),
	LR = tuple_to_list(Result),
	LEx = tuple_to_list(ExpectedResult),
	[
		?assert(abs(A - B) < min(abs(A), abs(B)) / 1000.0)
		|| {A, B} <- tl(lists:zip(LR, LEx))
	].


nayatani_test() ->
	ExpectedResult = #nayatani{lstar_p = 49.99988,
		lstar_n = 50.003915, c = 0.013355,
		h_angle = 257.5232, s = 0.013355,
		q = 62.62667, m = 0.016726,
		h_q = 288.17419,
		h_c_segment = g_b,
		h_c = 0.8188},

	Result = cbet:nayatani_model({19.01, 20.00, 21.78}, {95.05, 100.00, 108.88}, 20.0, 5000.0, 1000.0),
	LR = tuple_to_list(Result),
	LEx = tuple_to_list(ExpectedResult),
	[
		?assert(abs(A - B) < min(abs(A), abs(B)) / 1000.0)
		|| {A, B} <- tl(lists:zip(LR, LEx)), not is_atom(A)
	],
	?assertEqual(Result#nayatani.h_c_segment, ExpectedResult#nayatani.h_c_segment).


hunt_test() ->
	ExpectedResult = #hunt{j = 86.18995,c = 8.39282,
      h_angle = 208.39258,s = 4.319598,
      q = 101.77500,m = 8.59011,
      h_q = 264.5001786877803,q_wb = 92.83844494862979},


	Result = cbet:hunt_model({19.01, 20.00, 21.78}, {95.05, 100.00, 108.88}, {95.05, 100.00, 108.88}, 318.31, normal, #{cct_w => 6504, p => 1, s_w => 1, s => 2}),
	LR = tuple_to_list(Result),
	LEx = tuple_to_list(ExpectedResult),
	[
		?assert(abs(A - B) < min(abs(A), abs(B)) / 1000.0)
		|| {A, B} <- tl(lists:zip(LR, LEx)), not is_atom(A)
	].

%% ===================================================================
%% Вспомогательная функция для нормализации разницы hue (учитывает 360° цикл)
%% ===================================================================
normalize_hue_diff(Diff) ->
	abs(math:fmod(Diff + 180.0, 360.0) - 180.0).

